-- MySQL Script generated by MySQL Workbench
-- Thu Aug  4 00:32:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- curriculoSchema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`formacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formacao` (
  `idformação` INT NOT NULL,
  `niveldeensino` INT NOT NULL,
  `cursos` VARCHAR(45) NULL,
  `complemento` VARCHAR(500) NULL,
  PRIMARY KEY (`idformação`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atuacao` (
  `idAtuacao` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(50) NOT NULL,
  `empregoatual` VARCHAR(45) NULL,
  `empregos` VARCHAR(45) NULL,
  PRIMARY KEY (`idAtuacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projetosemandamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projetosemandamento` (
  `idprojetosemandamento` INT NOT NULL AUTO_INCREMENT,
  `datainicio` DATE NOT NULL,
  PRIMARY KEY (`idprojetosemandamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projetosterminados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projetosterminados` (
  `idprojetosterminados` INT NOT NULL AUTO_INCREMENT,
  `datainicio` DATE NOT NULL,
  `datatermino` DATE NOT NULL,
  PRIMARY KEY (`idprojetosterminados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projetos_pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projetos_pessoas` (
  `idprojetos` INT NOT NULL AUTO_INCREMENT,
  `projetosemandamento` INT NOT NULL,
  `projetosterminados` INT NOT NULL,
  PRIMARY KEY (`idprojetos`),
  INDEX `fk_projetos_pessoas_projetosemandamento1_idx` (`projetosemandamento` ASC),
  INDEX `fk_projetos_pessoas_projetosterminados1_idx` (`projetosterminados` ASC),
  CONSTRAINT `fk_projetos_pessoas_projetosemandamento1`
    FOREIGN KEY (`projetosemandamento`)
    REFERENCES `mydb`.`projetosemandamento` (`idprojetosemandamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projetos_pessoas_projetosterminados1`
    FOREIGN KEY (`projetosterminados`)
    REFERENCES `mydb`.`projetosterminados` (`idprojetosterminados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curriculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curriculo` (
  `idcurriculo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `resumo` VARCHAR(500) NOT NULL,
  `ultimaatualizacao` DATE NOT NULL,
  `Formacao` INT,
  `Atuacao` INT,
  `Projetos` INT,
  PRIMARY KEY (`idcurriculo`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_pessoas_formação_idx` (`Formacao` ASC),
  INDEX `fk_pessoas_Atuacao1_idx` (`Atuacao` ASC),
  INDEX `fk_pessoas_projetos1_idx` (`Projetos` ASC),
  CONSTRAINT `fk_pessoas_formação`
    FOREIGN KEY (`Formacao`)
    REFERENCES `mydb`.`formacao` (`idformação`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_Atuacao1`
    FOREIGN KEY (`Atuacao`)
    REFERENCES `mydb`.`Atuacao` (`idAtuacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_projetos1`
    FOREIGN KEY (`Projetos`)
    REFERENCES `mydb`.`projetos_pessoas` (`idprojetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `idcursos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `cargahoraria` INT NOT NULL,
  `link_certificado` VARCHAR(100) NOT NULL,
  `criador_curso` VARCHAR(45) NULL,
  PRIMARY KEY (`idcursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`formacao_has_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formacao_has_cursos` (
  `formação_idformação` INT NOT NULL AUTO_INCREMENT,
  `cursos_idcursos` INT NOT NULL,
  PRIMARY KEY (`formação_idformação`, `cursos_idcursos`),
  INDEX `fk_formação_has_cursos_cursos1_idx` (`cursos_idcursos` ASC),
  INDEX `fk_formação_has_cursos_formação1_idx` (`formação_idformação` ASC),
  CONSTRAINT `fk_formação_has_cursos_formação1`
    FOREIGN KEY (`formação_idformação`)
    REFERENCES `mydb`.`formacao` (`idformação`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formação_has_cursos_cursos1`
    FOREIGN KEY (`cursos_idcursos`)
    REFERENCES `mydb`.`cursos` (`idcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empregosanteriores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empregosanteriores` (
  `idempregosanteriores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Atuacao` INT NOT NULL,
  PRIMARY KEY (`idempregosanteriores`, `Atuacao`),
  INDEX `fk_empregosanteriores_Atuacao1_idx` (`Atuacao` ASC),
  CONSTRAINT `fk_empregosanteriores_Atuacao1`
    FOREIGN KEY (`Atuacao`)
    REFERENCES `mydb`.`Atuacao` (`idAtuacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projetos` (
  `idprojetos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `cargahoraria` VARCHAR(45) NOT NULL,
  `projetosemandamento` INT NOT NULL,
  `projetosterminados` INT NOT NULL,
  PRIMARY KEY (`idprojetos`, `projetosemandamento`, `projetosterminados`),
  INDEX `fk_projetos_projetosemandamento1_idx` (`projetosemandamento` ASC),
  INDEX `fk_projetos_projetosterminados1_idx` (`projetosterminados` ASC),
  CONSTRAINT `fk_projetos_projetosemandamento1`
    FOREIGN KEY (`projetosemandamento`)
    REFERENCES `mydb`.`projetosemandamento` (`idprojetosemandamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projetos_projetosterminados1`
    FOREIGN KEY (`projetosterminados`)
    REFERENCES `mydb`.`projetosterminados` (`idprojetosterminados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `createdate` DATE NULL DEFAULT CURRENT_TIMESTAMP,
  `curriculo` INT NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_users_curriculo1_idx` (`curriculo`),
  CONSTRAINT `fk_users_curriculo1`
    FOREIGN KEY (`curriculo`)
    REFERENCES `mydb`.`curriculo` (`idcurriculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
