CREATE DATABASE Site_lettes;

-- MySQL Script generated by MySQL Workbench
-- Sun Aug  7 15:23:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Site_lettes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Site_lettes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Site_lettes` DEFAULT CHARACTER SET utf8 ;
USE `Site_lettes` ;

-- -----------------------------------------------------
-- Table `Site_lettes`.`__nivel_ensino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`__nivel_ensino` (
  `id` INT NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site_lettes`.`formacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`formacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nivel_ensino` INT NOT NULL,
  `cursos` VARCHAR(45) NULL,
  `complemento` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_formacao___nivel_ensino1_idx` (`nivel_ensino` ASC),
  CONSTRAINT `fk_formacao___nivel_ensino1`
    FOREIGN KEY (`nivel_ensino`)
    REFERENCES `Site_lettes`.`__nivel_ensino` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site_lettes`.`__area_atuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`__area_atuacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `id__area_atuacao_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site_lettes`.`Atuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`Atuacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empregoatual` VARCHAR(45) NULL,
  `empregos` VARCHAR(45) NULL,
  `__area_atuacao` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Atuacao___area_atuacao1_idx` (`__area_atuacao` ASC),
  CONSTRAINT `fk_Atuacao___area_atuacao1`
    FOREIGN KEY (`__area_atuacao`)
    REFERENCES `Site_lettes`.`__area_atuacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site_lettes`.`projetosemandamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`projetosemandamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datainicio` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site_lettes`.`projetosterminados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`projetosterminados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datainicio` DATE NOT NULL,
  `datatermino` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site_lettes`.`projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`projetos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `projetosemandamento` INT NOT NULL,
  `projetosterminados` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projetos_pessoas_projetosemandamento1_idx` (`projetosemandamento` ASC),
  INDEX `fk_projetos_pessoas_projetosterminados1_idx` (`projetosterminados` ASC),
  CONSTRAINT `fk_projetos_pessoas_projetosemandamento1`
    FOREIGN KEY (`projetosemandamento`)
    REFERENCES `Site_lettes`.`projetosemandamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projetos_pessoas_projetosterminados1`
    FOREIGN KEY (`projetosterminados`)
    REFERENCES `Site_lettes`.`projetosterminados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site_lettes`.`curriculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`curriculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `resumo` VARCHAR(500) NOT NULL,
  `ultimaatualizacao` DATE NOT NULL,
  `Formacao` INT NOT NULL,
  `Atuacao` INT NOT NULL,
  `Projetos` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_pessoas_formação_idx` (`Formacao` ASC),
  INDEX `fk_pessoas_Atuacao1_idx` (`Atuacao` ASC),
  INDEX `fk_pessoas_projetos1_idx` (`Projetos` ASC),
  CONSTRAINT `fk_pessoas_formação`
    FOREIGN KEY (`Formacao`)
    REFERENCES `Site_lettes`.`formacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_Atuacao1`
    FOREIGN KEY (`Atuacao`)
    REFERENCES `Site_lettes`.`Atuacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_projetos1`
    FOREIGN KEY (`Projetos`)
    REFERENCES `Site_lettes`.`projetos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site_lettes`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `cargahoraria` INT NOT NULL,
  `link_certificado` VARCHAR(100) NOT NULL,
  `instituição` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site_lettes`.`formacao_has_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`formacao_has_cursos` (
  `formação_id` INT NOT NULL,
  `cursos_id` INT NOT NULL,
  PRIMARY KEY (`formação_id`, `cursos_id`),
  INDEX `fk_formação_has_cursos_cursos1_idx` (`cursos_id` ASC),
  INDEX `fk_formação_has_cursos_formação1_idx` (`formação_id` ASC),
  CONSTRAINT `fk_formação_has_cursos_formação1`
    FOREIGN KEY (`formação_id`)
    REFERENCES `Site_lettes`.`formacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formação_has_cursos_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `Site_lettes`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site_lettes`.`empregosanteriores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`empregosanteriores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Atuacao` INT NOT NULL,
  PRIMARY KEY (`id`, `Atuacao`),
  INDEX `fk_empregosanteriores_Atuacao1_idx` (`Atuacao` ASC),
  CONSTRAINT `fk_empregosanteriores_Atuacao1`
    FOREIGN KEY (`Atuacao`)
    REFERENCES `Site_lettes`.`Atuacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site_lettes`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `Site_lettes`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`projeto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `cargahoraria` VARCHAR(45) NOT NULL,
  `projetosemandamento` INT NOT NULL,
  `projetosterminados` INT NOT NULL,
  PRIMARY KEY (`id`, `projetosemandamento`, `projetosterminados`),
  INDEX `fk_projetos_projetosemandamento1_idx` (`projetosemandamento` ASC),
  INDEX `fk_projetos_projetosterminados1_idx` (`projetosterminados` ASC),
  CONSTRAINT `fk_projetos_projetosemandamento1`
    FOREIGN KEY (`projetosemandamento`)
    REFERENCES `Site_lettes`.`projetosemandamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projetos_projetosterminados1`
    FOREIGN KEY (`projetosterminados`)
    REFERENCES `Site_lettes`.`projetosterminados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Site_lettes`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Site_lettes`.`users` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `createdate` DATE NULL DEFAULT CURRENT_TIMESTAMP,
  `curriculo` INT,
  `iP` INT,
  INDEX `fk_users_curriculo1_idx` (`curriculo` ASC),
  CONSTRAINT `fk_users_curriculo1`
    FOREIGN KEY (`curriculo`)
    REFERENCES `Site_lettes`.`curriculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

